fix

diff --git a/.github/workflows/Openwrt-AutoBuild.yml b/.github/workflows/Openwrt-AutoBuild.yml
--- a/.github/workflows/Openwrt-AutoBuild.yml
+++ b/.github/workflows/Openwrt-AutoBuild.yml
@@ -241,15 +241,11 @@ jobs:
       id: kernel
       run: |
         cd openwrt
-        #KERNEL_VER=$(make -s kernelversion 2>/dev/null | head -n1 | tr -d '[:space:]' || true)
-        # 找到 include/kernel-* 下的版本文件
-        KERNEL_FILE=$(ls include/kernel-* | head -n1)
-        # 提取主版本号
-        BASE_VER=$(basename $KERNEL_FILE | cut -d'-' -f2)
-        # 提取补丁号
-        PATCH_VER=$(grep "^LINUX_VERSION-$BASE_VER" "$KERNEL_FILE" | cut -d= -f2 | tr -d ' .')
-        # 拼接完整版本号
-        KERNEL_FULL="$BASE_VER.$PATCH_VER"
+        KERNEL_FULL=$(make -s --no-print-directory -C target/linux TOPDIR="$PWD" val.LINUX_VERSION)
+        [[ "$KERNEL_FULL" =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?(-rc[0-9]+)?$ ]] || {
+          echo "Invalid kernel version: $KERNEL_FULL" >&2
+          exit 1
+        }
         echo "KERNEL_VER=$KERNEL_FULL" >> $GITHUB_ENV
         echo "Kernel full version detected: $KERNEL_FULL"
 
